name: Development Workflow

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Sync CI
        uses: joaogasparr/react-actions-ci-cd/.github/workflows/ci.yml
      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v3
        with:
          name: "artifact-${{ github.SHA }}"
          path: build

  deploy:
    runs-on: ubuntu-18.04
    needs: build
    steps:
      - name: Get the last artifact
        uses: actions/download-artifact@v3
        with:
          name: "artifact-${{ github.SHA }}"
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: "./"
          production-branch: develop
          production-deploy: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          fails-without-credentials: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
