name: Development Workflow

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Installing dependencies
        run: npm install
      - name: Running unit tests
        run: npm run test
      - name: Generate build
        run: npm run build --if-present
      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v3
        with:
          name: react-github-actions-build
          path: build

  deploy:
    runs-on: ubuntu-18.04
    needs: build
    steps:
      - name: Getting last artifact
        uses: actions/download-artifact@v3
        with:
          name: react-github-actions-build
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          production-branch: main
          production-deploy: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: ${{ github.event.pull_request.title }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1        
